---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: html-pdf-converter-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: html-pdf-converter
  {{ end }}
spec:
  {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
  replicas: 2
  {{ else }}
  replicas: 1
  {{ end }}
  selector:
    matchLabels:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      name: html-pdf-converter-{{ .DRONE_SOURCE_BRANCH }}
      {{ else }}
      name: html-pdf-converter
      {{ end }}
  template:
    metadata:
      labels:
        {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        name: html-pdf-converter-{{ .DRONE_SOURCE_BRANCH }}
        service: html-pdf-converter-{{ .DRONE_SOURCE_BRANCH }}
        {{ else }}
        name: html-pdf-converter
        service: html-pdf-converter
        {{ end }}
    spec:
      containers:
        {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        - name: html-pdf-converter-{{ .DRONE_SOURCE_BRANCH }}
        {{ else }}
        - name: html-pdf-converter
        {{ end }}
          # html-pdf-converter: v3.0.0 updated on 23/01/2024
          image: quay.io/ukhomeofficedigital/html-pdf-converter:3.0.0@sha256:2f13eb3bc9d396f2685e22a66b40613a44dfd9956412fe2752477601bb33772c
          imagePullPolicy: Always
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              cpu: 250m
              memory: 256Mi
          env:
            - name: APP_PORT
              value: "8001"
          volumeMounts:
            - mountPath: /public
              name: public
            - mountPath: /certs
              name: certs
              readOnly: true
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
          securityContext:
            runAsNonRoot: true

        - name: nginx-proxy
          # nginx-proxy-govuk:v4
          image: quay.io/ukhomeofficedigital/nginx-proxy-govuk@sha256:4470064d0b1d20ae08c5fd85551576cb687f342a22d6cb456fda9b2c4ce8c8df
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              cpu: 250m
              memory: 256Mi
          env:
            - name: PROXY_SERVICE_HOST
              value: 127.0.0.1
            - name: PROXY_SERVICE_PORT
              value: "8001"
            - name: ENABLE_UUID_PARAM
              value: "FALSE"
            - name: HTTPS_REDIRECT
              value: "FALSE"
            - name: NAXSI_USE_DEFAULT_RULES
              value: "FALSE"
            - name: PORT_IN_HOST_HEADER
              value: "FALSE"
            - name: ERROR_REDIRECT_CODES
              value: "599"
            - name: SERVER_CERT
              value: /certs/tls.crt
            - name: SERVER_KEY
              value: /certs/tls.key
            - name: ADD_NGINX_SERVER_CFG
              value: |-
                resolver 8.8.8.8 8.8.4.4;
                ssl_stapling_verify on;
                ssl_stapling_responder http://x1.i.lencr.org;
                ssl_certificate /certs/tls.crt;
                ssl_certificate_key /certs/tls.key;
                ssl_trusted_certificate /certs/tls.crt;
          volumeMounts:
            - mountPath: /public
              name: public
            - mountPath: /certs
              name: certs
              readOnly: true
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true      
          securityContext:
            runAsNonRoot: true
          ports:
            - containerPort: 10080
            - containerPort: 10443
      volumes:
        - name: public
          emptyDir: {}
        - name: certs
          secret:
            {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
            secretName: tls
            {{ else }}
            secretName: tls-cert
            {{ end }}
        - name: bundle
          configMap:
            name: bundle
