pipeline:

  unit_test:
    image: node
    commands:
      - npm install
      - npm test
    when:
      event: push
      branch: [ master, development ]

  create_artefact:
    image: quay.io/ukhomeofficedigital/ecr:latest
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/sas/refugee-integration-loans
    tags:
      - latest_${DRONE_BRANCH}
      - ${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: [ master, development ]

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    secrets:
      - kube_token_ril_acp_notprod
    environment:
      - KUBE_NAMESPACE=sas-ril-dev
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    commands:
      - export KUBE_TOKEN=$${KUBE_TOKEN_RIL_ACP_NOTPROD}
      - kd --insecure-skip-tls-verify -f kube/redis-service.yml -f kube/redis-network-policy.yml -f kube/redis-deployment.yml
      - kd --insecure-skip-tls-verify -f kube/dev/configmap.yaml -f kube/dev/ingress-internal.yaml -f kube/networkpolicy-internal.yaml -f kube/service.yaml
      - kd --insecure-skip-tls-verify --timeout 10m --check-interval 10s -f kube/dev/deployment.yaml
    when:
      event: push
      branch: master

  deploy_to_branch:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    secrets:
      - kube_token_ril_acp_notprod
    environment:
      - KUBE_NAMESPACE=sas-ril-branch
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    commands:
      - export KUBE_TOKEN=$${KUBE_TOKEN_RIL_ACP_NOTPROD}
      - kd --insecure-skip-tls-verify -f kube/redis-service.yml -f kube/redis-network-policy.yml -f kube/redis-deployment.yml
      - kd --insecure-skip-tls-verify -f kube/branch/configmap.yaml -f kube/branch/ingress-internal.yaml -f kube/networkpolicy-internal.yaml -f kube/service.yaml
      - kd --insecure-skip-tls-verify --timeout 10m --check-interval 10s -f kube/branch/deployment.yaml
    when:
      event: push
      branch: development

  deploy_to_uat:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    secrets:
      - kube_token_ril_acp_notprod
    environment:
      - KUBE_NAMESPACE=sas-ril-uat
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    commands:
      - export KUBE_TOKEN=$${KUBE_TOKEN_RIL_ACP_NOTPROD}
      - kd --insecure-skip-tls-verify -f kube/redis-service.yml -f kube/redis-network-policy.yml -f kube/redis-deployment.yml
      - kd --insecure-skip-tls-verify -f kube/uat/configmap.yaml -f kube/uat/ingress-internal.yaml -f kube/networkpolicy-internal.yaml -f kube/service.yaml
      - kd --insecure-skip-tls-verify --timeout 10m --check-interval 10s -f kube/uat/deployment.yaml
    when:
      environment: UAT
      event: deployment

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    secrets:
      - kube_token_ril_acp_prod
    environment:
      - KUBE_NAMESPACE=sas-ril-prod
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    commands:
      - export KUBE_TOKEN=$${KUBE_TOKEN_RIL_ACP_PROD}
      - kd --insecure-skip-tls-verify -f kube/redis-service.yml -f kube/redis-network-policy.yml -f kube/redis-deployment.yml
      - kd --insecure-skip-tls-verify -f kube/prod/configmap.yaml -f kube/prod/ingress-external.yaml -f kube/networkpolicy-external.yaml -f kube/service.yaml
      - kd --insecure-skip-tls-verify --timeout 10m --check-interval 10s -f kube/prod/deployment.yaml
    when:
      environment: PROD
      event: deployment

  manual_deploy_to_branch:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    secrets:
      - kube_token_ril_acp_notprod
    environment:
      - KUBE_NAMESPACE=sas-ril-branch
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    commands:
      - export KUBE_TOKEN=$${KUBE_TOKEN_RIL_ACP_NOTPROD}
      - kd --insecure-skip-tls-verify -f kube/redis-service.yml -f kube/redis-network-policy.yml -f kube/redis-deployment.yml
      - kd --insecure-skip-tls-verify -f kube/branch/configmap.yaml -f kube/branch/ingress-internal.yaml -f kube/networkpolicy-internal.yaml -f kube/service.yaml
      - kd --insecure-skip-tls-verify --timeout 10m --check-interval 10s -f kube/branch/deployment.yaml
    when:
      environment: BRANCH
      event: deployment

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner-node:latest
    failure: ignore
    when:
      event: push
      branch: master

  notify_slack_build:
    image: plugins/slack:1.1
    failure: ignore
    secrets:
      - SLACK_WEBHOOK
    channel: refugee-integration-loan-build
    username: Drone
    icon_url: http://readme.drone.io/0.5/logo_dark.svg
    icon.url: http://readme.drone.io/0.5/logo_dark.svg
    template: >
      BUILD on {{build.event}} of RIL has {{build.status}} - <{{build.link}}|#{{build.number}}>
      {{#success build.status}}
        :thumbsup: :thumbsup: :thumbsup:
      {{else}}
        :x: :x: :x:
      {{/success}}
      Author: {{build.author}}


      Duration: {{since job.started}}\n


      Job: <{{build.link}}|#{{build.number}}>\n


      Commit: {{build.commit}}
    when:
      branch: master
      event: push

  notify_slack_deploy:
    image: plugins/slack:1.1
    failure: ignore
    secrets:
      - SLACK_WEBHOOK
    channel: refugee-integration-loan-build
    username: Drone
    icon_url: http://readme.drone.io/0.5/logo_dark.svg
    icon.url: http://readme.drone.io/0.5/logo_dark.svg
    template: >
      DEPLOY to {{deploy.to}} of RIL has {{build.status}} - <{{build.link}}|#{{build.number}}>
      {{#success build.status}}
        :thumbsup: :thumbsup: :thumbsup:
      {{else}}
        :x: :x: :x:
      {{/success}}
      Author: {{build.author}}


      Duration: {{since job.started}}


      Job: <{{build.link}}|#{{build.number}}>


      Commit: {{build.commit}}
    when:
      event: deployment
