pipeline:
  unit_test:
    image: node
    commands:
      - npm install
      - npm test
    when:
      event: push
      branch: master

  create_artefact:
    image: quay.io/ukhomeofficedigital/ecr:latest
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/cto/refugee-integration-loans
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    secrets:
      - kube_token_acp_notprod
    environment:
      - IMAGE_URL=340268328991.dkr.ecr.eu-west-2.amazonaws.com/cto/refugee-integration-loans:${DRONE_COMMIT_SHA}
      - DRONE_DEPLOY_TO=acp-notprod
    commands:
      - apk update
      - apk add curl
      - bin/deploy.sh
    when:
      event: push
      branch: master

  deploy_to_uat:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    commands:
      - echo "Deploy to UAT to be implemented"
    when:
      environment: UAT
      event: deployment

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    commands:
      - echo "Deploy to PROD to be implemented"
    when:
      environment: PROD
      event: deployment

  # SLACK WEBHOOK NOTIFICATIONS
  notify_slack:
    image: plugins/slack:1.1
    secrets:
      - SLACK_WEBHOOK
    channel: refugee-integration-loan-build
    username: Drone
    icon_url: http://readme.drone.io/0.5/logo_dark.svg
    icon.url: http://readme.drone.io/0.5/logo_dark.svg
    template: >
      *{{build.event}} <SERVICE_NAME> to {{deploy.to}} has {{build.status}} - <{{build.link}}|#{{build.number}}>

      Author: {{build.author}}

      Duration: {{since job.started}}
      Job: <{{build.link}}|#{{build.number}}>

      Commit: {{build.commit}}
    when:
      branch: master
      event: [push, deployment]