---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .NAME }}-internal
  labels:
    cert-manager.io/solver: route53
  annotations:
    cert-manager.io/enabled: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx-internal"
    ingress.kubernetes.io/add-base-url: "true"
    ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - {{ .NAME }}-dev.internal.cto-notprod.homeoffice.gov.uk
      secretName: {{ .NAME }}-internal
  rules:
    - host: {{ .NAME }}-dev.internal.cto-notprod.homeoffice.gov.uk
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .NAME }}
              servicePort: 443
            path: /apply
