---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: ingress-network-policy-internal-refugee-loan-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: ingress-network-policy-internal-refugee-loan
  {{ end }}
spec:
  podSelector:
    matchLabels:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      name: refugee-loan-{{ .DRONE_SOURCE_BRANCH }}
      {{ else }}
      name: refugee-loan
      {{ end }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-internal
      ports:
        - protocol: TCP
          port: 8080
