---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .NAME }}
  template:
    metadata:
      labels:
        name: {{ .NAME }}
        service: redis
    spec:
      containers:
        - name: {{ .NAME }}
          image: quay.io/ukhomeofficedigital/redis:v1.0.1
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /var/lib/redis
              name: data
          securityContext:
            runAsNonRoot: true
      volumes:
        - name: data
          emptyDir: {}
