---
apiVersion: v1
kind: Service
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: refugee-loan-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: refugee-loan
  {{ end }}
spec:
  selector:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    name: refugee-loan-{{ .DRONE_SOURCE_BRANCH }}
    {{ else }}
    name: refugee-loan
    {{ end }}
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 8080
